### ISSUE TITLE
firmware: i2c_th do not compile with avr-g++ 7.2.0

### ISSUE THREAD

**Issue by pat1** [r-map/rmap#279]
```
"/usr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega644p -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_PLUS -DARDUINO_ARCH_AVR -DSERIAL_TX_BUFFER_SIZE=192 -DSERIAL_RX_BUFFER_SIZE=192 -fno-strict-aliasing  "-I/home/pat1/git/rmap/arduino/sketchbook/hardware/Microduino/avr/cores/arduino" "-I/home/pat1/git/rmap/arduino/sketchbook/hardware/Microduino/avr/variants/plus" "-I/home/pat1/git/rmap/arduino/sketchbook/libraries/RmapConfig" "-I/home/pat1/git/rmap/arduino/sketchbook/libraries/Rmap" "-I/home/pat1/git/rmap/arduino/sketchbook/libraries/LiquidCrystal_I2C" "-I/home/pat1/git/rmap/arduino/sketchbook/hardware/Microduino/avr/libraries/Wire/src" "-I/home/pat1/git/rmap/arduino/sketchbook/libraries/Time" "-I/home/pat1/git/rmap/arduino/sketchbook/libraries/SensorDriver" "-I/home/pat1/git/rmap/arduino/sketchbook/libraries/HYT2X1" "-I/home/pat1/git/rmap/arduino/sketchbook/libraries/SdFat/src" "-I/home/pat1/git/rmap/arduino/sketchbook/hardware/Microduino/avr/libraries/_10_System_SPI" "/tmp/arduino_build_68752/sketch/i2c-th.ino.cpp" -o "/tmp/arduino_build_68752/sketch/i2c-th.ino.cpp.o"
In file included from /tmp/arduino_build_68752/sketch/i2c-th.h:39:0,
                 from /home/pat1/git/rmap/arduino/sketchbook/rmap/i2c-th/i2c-th.ino:31:
/home/pat1/git/rmap/arduino/sketchbook/libraries/SensorDriver/SensorDriver.h:258:19: error: flexible array member 'SensorDriver::values' not at end of 'class SensorDriver'
    int32_t values[];
                   ^
/home/pat1/git/rmap/arduino/sketchbook/libraries/SensorDriver/SensorDriver.h:258:19: error: flexible array member 'SensorDriver::values' not at end of 'class SensorDriverAdt7420'
/home/pat1/git/rmap/arduino/sketchbook/libraries/SensorDriver/SensorDriver.h:258:19: error: flexible array member 'SensorDriver::values' not at end of 'class SensorDriverHih6100'
/home/pat1/git/rmap/arduino/sketchbook/libraries/SensorDriver/SensorDriver.h:258:19: error: flexible array member 'SensorDriver::values' not at end of 'class SensorDriverHyt2X1'
Più di una libreria trovata per "TimeLib.h"
Usata: /home/pat1/git/rmap/arduino/sketchbook/libraries/Time
Non usata: /home/pat1/git/rmap/arduino/sketchbook/hardware/Microduino/avr/libraries/_09_DATA_Time
Non usata: /home/pat1/git/rmap/arduino/sketchbook/hardware/Microduino/avr/libraries/_09_DATA_Time
Non usata: /home/pat1/git/rmap/arduino/sketchbook/hardware/Microduino/avr/libraries/_09_DATA_Time
Non usata: /home/pat1/git/rmap/arduino/sketchbook/hardware/Microduino/avr/libraries/_09_DATA_Time
Uso la libreria RmapConfig nella cartella: /home/pat1/git/rmap/arduino/sketchbook/libraries/RmapConfig (legacy)
Uso la libreria Rmap nella cartella: /home/pat1/git/rmap/arduino/sketchbook/libraries/Rmap (legacy)
Uso la libreria LiquidCrystal_I2C alla versione 1.1.2 nella cartella: /home/pat1/git/rmap/arduino/sketchbook/libraries/LiquidCrystal_I2C 
Uso la libreria Wire alla versione 1.0 nella cartella: /home/pat1/git/rmap/arduino/sketchbook/hardware/Microduino/avr/libraries/Wire 
Uso la libreria Time alla versione 1.5 nella cartella: /home/pat1/git/rmap/arduino/sketchbook/libraries/Time 
Uso la libreria SensorDriver nella cartella: /home/pat1/git/rmap/arduino/sketchbook/libraries/SensorDriver (legacy)
Uso la libreria HYT2X1 nella cartella: /home/pat1/git/rmap/arduino/sketchbook/libraries/HYT2X1 (legacy)
Uso la libreria SdFat alla versione 1.0.3 nella cartella: /home/pat1/git/rmap/arduino/sketchbook/libraries/SdFat 
Uso la libreria _10_System_SPI nella cartella: /home/pat1/git/rmap/arduino/sketchbook/hardware/Microduino/avr/libraries/_10_System_SPI (legacy)
exit status 1
Errore durante la compilazione per la scheda Microduino/mCookie-Core+ (644pa).
```

**Comment by pat1** [comment]
Continua a non compilare:
/usr/bin/avr-g++ --version
avr-g++ (Fedora 9.2.0-1.fc30) 9.2.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


`
"/usr/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega1284p -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_PLUS -DARDUINO_ARCH_AVR -DSERIAL_TX_BUFFER_SIZE=192 -DSERIAL_RX_BUFFER_SIZE=192 -fno-strict-aliasing  -std=c++11  "-I/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/hardware/Microduino/avr/cores/arduino" "-I/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/hardware/Microduino/avr/variants/plus" "-I/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/libraries/RmapConfig" "-I/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/libraries/Rmap" "-I/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/libraries/LiquidCrystal_I2C" "-I/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/hardware/Microduino/avr/libraries/Wire/src" "-I/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/hardware/Microduino/avr/libraries/SPI/src" "-I/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/libraries/SdFat/src" "-I/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/libraries/Time" "-I/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/libraries/PCF8563" "-I/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/libraries/NTP" "-I/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/libraries/Ethernet2/src" "-I/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/libraries/sim800" "-I/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/libraries/ArduinoJson/src" "-I/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/libraries/SensorDriver" "-I/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/libraries/Registers" "-I/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/libraries/arduinoJsonRPC" "-I/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/libraries/MQTTClient" "/tmp/arduino_build_447733/sketch/stima.ino.cpp" -o "/tmp/arduino_build_447733/sketch/stima.ino.cpp.o"
In file included from /tmp/arduino_build_447733/sketch/stima.h:57,
                 from /autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/stima_v3/stima/stima.ino:37:
/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/libraries/SensorDriver/SensorDriver.h:260:12: error: flexible array member 'SensorDriver::values' not at end of 'class SensorDriver'
  260 |    int32_t values[];
      |            ^~~~~~
/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/libraries/SensorDriver/SensorDriver.h:260:12: error: flexible array member 'SensorDriver::values' not at end of 'class SensorDriverAdt7420'
/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/libraries/SensorDriver/SensorDriver.h:260:12: error: flexible array member 'SensorDriver::values' not at end of 'class SensorDriverHih6100'
/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/libraries/SensorDriver/SensorDriver.h:260:12: error: flexible array member 'SensorDriver::values' not at end of 'class SensorDriverDw1'
/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/libraries/SensorDriver/SensorDriver.h:260:12: error: flexible array member 'SensorDriver::values' not at end of 'class SensorDriverRain'
/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/libraries/SensorDriver/SensorDriver.h:260:12: error: flexible array member 'SensorDriver::values' not at end of 'class SensorDriverTh'
/autofs/nfshomes/ppatruno/git/rmap/arduino/sketchbook/libraries/SensorDriver/SensorDriver.h:260:12: error: flexible array member 'SensorDriver::values' not at end of 'class SensorDriverOpc'
`

**Comment by pat1** [comment]
https://stackoverflow.com/questions/37164358/error-flexible-array-member-not-at-end-of-struct

**Comment by pat1** [comment]
commit de30915 solve the problem.
Dopo un anno e mezzo che non si riesce a compilare stima v3 ho dovuto fare qualche cosa.
La modifica è da testare e non so se sia una buona soluzione e per questo il bug rimane aperto.
Usare comunque un flexible array come membro di una classe non è una scelta ottimale.

**Comment by pat1** [comment]
https://thephd.github.io/vendor/future_cxx/papers/d1039.html#motivation

C99 defined Flexible Array Members (FAMs), a way of having a dynamic array of similarly typed data laid out in a contiguous, flat format beyond an initial sequence in a struct. Flexible Array Members have been used to great success to interface with many low-latency networking and binary protocols and formats, making it the go-to choice for working with large amounts of data prefixed by header values. 
...
Despite this success, nothing like this exists in C++, making its usage unspecified behavior by omission. All compilers warn or error about its usage when working with C from C++ that uses it, making it hard to confidently employ the C technique in C++ code bases. This presents a fairly painful chasm between what is possible in C and what is possible in C++, and prevents Bjarne Stroustrup’s earliest vision of making it possible to fully cover and subsume all of C with C++.

**Comment by pat1** [comment]
il commit è stato effettuato nell'albero obsoleto arduino e non in platformio
